package com.skb.view;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author shishir
 */
public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();

        //My Code
        pnlLoadingScreen.setVisible(false);
        setTitle("Login Screen");
        setLocationRelativeTo(null); // this method display the JFrame to center position of a screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLoadingScreen = new javax.swing.JPanel();
        lblLoggingIn = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        lblLoadingImage = new javax.swing.JLabel();
        pnlLoginScreenForegroundWhiteRectangle = new javax.swing.JPanel();
        lblLoginScreenLoginText = new javax.swing.JLabel();
        lblLoginScreenUsername = new javax.swing.JLabel();
        lblLoginScreenPassword = new javax.swing.JLabel();
        textFieldLoginScreenUsername = new javax.swing.JTextField();
        textFieldLoginScreenPassword = new javax.swing.JTextField();
        btnLoginScreenLogin = new javax.swing.JButton();
        lblLoginScreenForgotPassword = new javax.swing.JLabel();
        lblLoginScreenPasswordIsIncorrect = new javax.swing.JLabel();
        lblLoginScreenUsernameIsIncorrect = new javax.swing.JLabel();
        lblLoginScreenBgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlLoadingScreen.setBackground(new java.awt.Color(148, 183, 58));
        pnlLoadingScreen.setMaximumSize(new java.awt.Dimension(1280, 720));
        pnlLoadingScreen.setMinimumSize(new java.awt.Dimension(1280, 720));
        pnlLoadingScreen.setPreferredSize(new java.awt.Dimension(1280, 720));
        pnlLoadingScreen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLoggingIn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLoggingIn.setForeground(new java.awt.Color(255, 255, 255));
        lblLoggingIn.setText("Logging in.....");
        pnlLoadingScreen.add(lblLoggingIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 500, -1, -1));

        progressBar.setBackground(new java.awt.Color(102, 255, 102));
        progressBar.setForeground(new java.awt.Color(0, 255, 153));
        progressBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlLoadingScreen.add(progressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 560, 940, 40));

        lblLoadingImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/skb/resoruces/loadingImage.png"))); // NOI18N
        pnlLoadingScreen.add(lblLoadingImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, -1));

        getContentPane().add(pnlLoadingScreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlLoginScreenForegroundWhiteRectangle.setBackground(new java.awt.Color(255, 255, 255));
        pnlLoginScreenForegroundWhiteRectangle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLoginScreenLoginText.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        lblLoginScreenLoginText.setText("Login");
        pnlLoginScreenForegroundWhiteRectangle.add(lblLoginScreenLoginText, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        lblLoginScreenUsername.setForeground(new java.awt.Color(51, 51, 51));
        lblLoginScreenUsername.setText("Username");
        pnlLoginScreenForegroundWhiteRectangle.add(lblLoginScreenUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        lblLoginScreenPassword.setForeground(new java.awt.Color(51, 51, 51));
        lblLoginScreenPassword.setText("Password");
        pnlLoginScreenForegroundWhiteRectangle.add(lblLoginScreenPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));
        pnlLoginScreenForegroundWhiteRectangle.add(textFieldLoginScreenUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 260, 50));
        pnlLoginScreenForegroundWhiteRectangle.add(textFieldLoginScreenPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 260, 50));

        btnLoginScreenLogin.setBackground(new java.awt.Color(254, 254, 254));
        btnLoginScreenLogin.setText("LOGIN");
        btnLoginScreenLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginScreenLoginActionPerformed(evt);
            }
        });
        pnlLoginScreenForegroundWhiteRectangle.add(btnLoginScreenLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 250, 40));

        lblLoginScreenForgotPassword.setForeground(new java.awt.Color(153, 153, 153));
        lblLoginScreenForgotPassword.setText("forgot password?");
        pnlLoginScreenForegroundWhiteRectangle.add(lblLoginScreenForgotPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, -1, -1));

        lblLoginScreenPasswordIsIncorrect.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblLoginScreenPasswordIsIncorrect.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginScreenPasswordIsIncorrect.setText("password is incorrect");
        pnlLoginScreenForegroundWhiteRectangle.add(lblLoginScreenPasswordIsIncorrect, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, -1, -1));

        lblLoginScreenUsernameIsIncorrect.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblLoginScreenUsernameIsIncorrect.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginScreenUsernameIsIncorrect.setText("username is incorrect");
        pnlLoginScreenForegroundWhiteRectangle.add(lblLoginScreenUsernameIsIncorrect, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        getContentPane().add(pnlLoginScreenForegroundWhiteRectangle, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 380, 530));

        lblLoginScreenBgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/skb/resoruces/loginScreenBgImage.jpg"))); // NOI18N
        lblLoginScreenBgImage.setText(" ");
        getContentPane().add(lblLoginScreenBgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginScreenLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginScreenLoginActionPerformed
        // Sample data for validation (replace this with your actual data source)
        String validUsername = "";
        String validPassword = "";

        // Retrieve input from username and password fields
        String enteredUsername = textFieldLoginScreenUsername.getText();
        String enteredPassword = textFieldLoginScreenPassword.getText();

        // Reset error labels
        lblLoginScreenUsernameIsIncorrect.setText("");
        lblLoginScreenPasswordIsIncorrect.setText("");

        // Validate username
        if (enteredUsername.equals(validUsername) == false) {
            lblLoginScreenUsernameIsIncorrect.setText("Username is incorrect");
            lblLoginScreenUsernameIsIncorrect.setForeground(java.awt.Color.RED);
        }

        // Validate password
        if (enteredPassword.equals(validPassword) == false) {
            lblLoginScreenPasswordIsIncorrect.setText("Password is incorrect");
            lblLoginScreenPasswordIsIncorrect.setForeground(java.awt.Color.RED);
        }

        // Check if both username and password are correct
        if (enteredUsername.equals(validUsername) && enteredPassword.equals(validPassword)) {
            // Logic for successful login (navigate to the next screen or show a success message)
            javax.swing.JOptionPane.showMessageDialog(this, "Login successful!", "Success", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            pnlLoginScreenForegroundWhiteRectangle.setVisible(false);
            startProgress();

        }
    }//GEN-LAST:event_btnLoginScreenLoginActionPerformed

    private void startProgress() {
        pnlLoadingScreen.setVisible(true);
        javax.swing.SwingWorker<Void, Integer> worker = new javax.swing.SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(30); // Simulated delay for progress bar
                    publish(i); // Publish progress
                }
                return null;
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int progress = chunks.get(chunks.size() - 1);
                progressBar.setValue(progress);
            }

            @Override
            protected void done() {
                MainScreen mainScreen = new MainScreen();
                mainScreen.setVisible(true);

                // Close the Login Screen JFrame
                LoginScreen.this.setVisible(false); // Dispose of the current JFrame
                LoginScreen.this.dispose(); // Optional: Free up resources
            }
        };
        worker.execute(); // Start the worker thread
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoginScreenLogin;
    private javax.swing.JLabel lblLoadingImage;
    private javax.swing.JLabel lblLoggingIn;
    private javax.swing.JLabel lblLoginScreenBgImage;
    private javax.swing.JLabel lblLoginScreenForgotPassword;
    private javax.swing.JLabel lblLoginScreenLoginText;
    private javax.swing.JLabel lblLoginScreenPassword;
    private javax.swing.JLabel lblLoginScreenPasswordIsIncorrect;
    private javax.swing.JLabel lblLoginScreenUsername;
    private javax.swing.JLabel lblLoginScreenUsernameIsIncorrect;
    private javax.swing.JPanel pnlLoadingScreen;
    private javax.swing.JPanel pnlLoginScreenForegroundWhiteRectangle;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JTextField textFieldLoginScreenPassword;
    private javax.swing.JTextField textFieldLoginScreenUsername;
    // End of variables declaration//GEN-END:variables
}
